### ISSUE TITLE
plothover is not working

### ISSUE THREAD

**Issue by dvanderfaeillie** [mojoaxel/flot-bubbles#2]
Hi guys,
I've encountered a small issue, hovering over a bubble does not seem to return any item.

Minimal working example at JSFiddle:
http://jsfiddle.net/dietervdf/5yk3pw3n/1/

the console is filled with null values. Any way to solve this?

**Comment by mojoaxel** [comment]
thx. I'll have a look tomorrow.

**Comment by mojoaxel** [comment]
@dvanderfaeillie Here your working example: https://jsfiddle.net/delphiN/qd3sayLe/

**Comment by dvanderfaeillie** [comment]
@mojoaxel Points with `y = 0` seem to generate issues...
https://jsfiddle.net/dietervdf/qd3sayLe/1/

**Comment by mojoaxel** [comment]
Sadly this is also an issue for `x == 0`
will fix...
