### ISSUE TITLE
Requires Integers, not decimals?

### ISSUE THREAD

**Issue by gstoa** [mojoaxel/flot-bubbles#7]
Can you please confirm that the data array can only use integers, not decimals?  If so, how do you recommend I plot the following values:

d1 = array([1, 1.40, 10], [2, 1.50, 10], [3, 1.25, 10], [4, 1.80, 10]);

**Comment by mojoaxel** [comment]
> Can you please confirm that the data array can only use integers, not decimals?

No, I see no reasons why decimal values could not be used.

The problem with your data is that the data value 10 is much bigger than the scale of the y-axes values 1.25-1.80. The bubbles are much, much to big this way. I would recommend multiplying the y-axes by 100:

`d1 = [[1, 140, 10], [2, 150, 10], [3, 125, 10], [4, 180, 10]];`
![image](https://user-images.githubusercontent.com/600565/34653270-ece8a5c2-f3e9-11e7-9bb1-95a1ba6f3443.png)
http://jsbin.com/mobaha/1/edit?html,output

Or you could reduce the value to get a similar result:

`var d1 = [[1, 1.40, 0.1], [2, 1.50, 0.1], [3, 1.25, 0.1], [4, 1.80, 0.1]];`
![image](https://user-images.githubusercontent.com/600565/34653288-375b5cd0-f3ea-11e7-872d-f8be6ed412fe.png)
http://jsbin.com/mobaha/2/edit?html,output
